package main

// Usage:
// export GMAIL_CLIENT_ID="your-client-id"
// export GMAIL_CLIENT_SECRET="your-client-secret"
// export GMAIL_RECIPIENT_EMAIL="recipient@example.com"  # Email to send test messages to
// go run main.go

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/danielrivera/mailbridge-go/core"
	"github.com/danielrivera/mailbridge-go/gmail"
	"golang.org/x/oauth2"
)

func main() {
	ctx := context.Background()

	// Load configuration from environment
	config := &gmail.Config{
		ClientID:     os.Getenv("GMAIL_CLIENT_ID"),
		ClientSecret: os.Getenv("GMAIL_CLIENT_SECRET"),
		RedirectURL:  "http://localhost",
		Scopes:       gmail.DefaultScopes(),
	}

	// Get recipient email from environment
	recipientEmail := os.Getenv("GMAIL_RECIPIENT_EMAIL")
	if recipientEmail == "" {
		log.Fatal("GMAIL_RECIPIENT_EMAIL environment variable is required")
	}

	// Create client
	client, err := gmail.New(config)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer func() {
		if err := client.Close(); err != nil {
			log.Printf("Error closing client: %v", err)
		}
	}()

	// Load or create token
	token, err := loadToken()
	if err != nil {
		log.Printf("No existing token found. Starting OAuth flow...")
		token, err = performOAuthFlow(ctx, client)
		if err != nil {
			log.Printf("OAuth flow failed: %v", err)
			return
		}
		if err := saveToken(token); err != nil {
			log.Printf("Warning: Failed to save token: %v", err)
		}
	}

	// Connect with token
	if err := client.ConnectWithToken(ctx, token); err != nil {
		log.Printf("Failed to connect: %v", err)
		return
	}

	fmt.Println("✅ Connected to Gmail successfully!")
	fmt.Println()

	fmt.Printf("📬 Sending test emails to: %s\n\n", recipientEmail)

	// Example 1: Send simple text email
	fmt.Println("📧 Example 1: Sending simple text email...")
	sendSimpleEmail(ctx, client, recipientEmail)

	// Example 2: Send HTML email
	fmt.Println("\n📧 Example 2: Sending HTML email...")
	sendHTMLEmail(ctx, client, recipientEmail)

	// Example 3: Send email with CC and BCC
	fmt.Println("\n📧 Example 3: Sending email with CC/BCC...")
	sendEmailWithCCBCC(ctx, client, recipientEmail)

	// Example 4: Send email with attachment
	fmt.Println("\n📧 Example 4: Sending email with attachment...")
	sendEmailWithAttachment(ctx, client, recipientEmail)

	// Example 5: Send email with custom headers
	fmt.Println("\n📧 Example 5: Sending email with custom headers...")
	sendEmailWithHeaders(ctx, client, recipientEmail)

	fmt.Println("\n✅ All examples completed successfully!")
}

func sendSimpleEmail(ctx context.Context, client *gmail.Client, recipientEmail string) {
	draft := &core.Draft{
		To:      []core.EmailAddress{{Email: recipientEmail}},
		Subject: "Test Email from MailBridge",
		Body:    core.EmailBody{Text: "Hello! This is a test email sent using MailBridge Go library."},
	}

	response, err := client.SendMessage(ctx, draft, nil)
	if err != nil {
		log.Printf("❌ Failed to send: %v", err)
		return
	}

	fmt.Printf("✅ Email sent! Message ID: %s, Thread ID: %s\n", response.ID, response.ThreadID)
}

func sendHTMLEmail(ctx context.Context, client *gmail.Client, recipientEmail string) {
	draft := &core.Draft{
		To:      []core.EmailAddress{{Email: recipientEmail}},
		Subject: "Newsletter - January 2026",
		Body: core.EmailBody{
			Text: "Welcome to our January newsletter!\n\nThis is the plain text version.",
			HTML: `<html>
<body>
	<h1>Newsletter - January 2026</h1>
	<p>Welcome to our <strong>January newsletter</strong>!</p>
	<ul>
		<li>Feature 1: New dashboard</li>
		<li>Feature 2: Improved performance</li>
		<li>Feature 3: Bug fixes</li>
	</ul>
	<p>Best regards,<br>The Team</p>
</body>
</html>`,
		},
	}

	response, err := client.SendMessage(ctx, draft, nil)
	if err != nil {
		log.Printf("❌ Failed to send: %v", err)
		return
	}

	fmt.Printf("✅ HTML email sent! Message ID: %s\n", response.ID)
}

func sendEmailWithCCBCC(ctx context.Context, client *gmail.Client, recipientEmail string) {
	draft := &core.Draft{
		To: []core.EmailAddress{
			{Email: recipientEmail},
		},
		Cc: []core.EmailAddress{
			{Email: recipientEmail},
		},
		Bcc: []core.EmailAddress{
			{Email: recipientEmail},
		},
		Subject: "Meeting Notes - January 26",
		Body:    core.EmailBody{Text: "Please find the meeting notes attached."},
	}

	response, err := client.SendMessage(ctx, draft, nil)
	if err != nil {
		log.Printf("❌ Failed to send: %v", err)
		return
	}

	fmt.Printf("✅ Email with CC/BCC sent! Message ID: %s\n", response.ID)
}

func sendEmailWithAttachment(ctx context.Context, client *gmail.Client, recipientEmail string) {
	// Create a sample text file as attachment
	attachmentData := []byte("This is a sample text file content.\n\nGenerated by MailBridge example.")

	draft := &core.Draft{
		To:      []core.EmailAddress{{Email: recipientEmail}},
		Subject: "Document Attached",
		Body:    core.EmailBody{Text: "Please see the attached document."},
		Attachments: []core.Attachment{
			{
				Filename: "sample.txt",
				MimeType: "text/plain",
				Data:     attachmentData,
			},
		},
	}

	response, err := client.SendMessage(ctx, draft, nil)
	if err != nil {
		log.Printf("❌ Failed to send: %v", err)
		return
	}

	fmt.Printf("✅ Email with attachment sent! Message ID: %s\n", response.ID)
}

func sendEmailWithHeaders(ctx context.Context, client *gmail.Client, recipientEmail string) {
	draft := &core.Draft{
		To:      []core.EmailAddress{{Email: recipientEmail}},
		ReplyTo: []core.EmailAddress{{Email: recipientEmail}},
		Subject: "Important: System Notification",
		Body:    core.EmailBody{Text: "This is an important system notification."},
	}

	opts := &core.SendOptions{
		CustomHeaders: map[string]string{
			"X-Priority": "1",
			"X-Mailer":   "MailBridge/1.0",
		},
	}

	response, err := client.SendMessage(ctx, draft, opts)
	if err != nil {
		log.Printf("❌ Failed to send: %v", err)
		return
	}

	fmt.Printf("✅ Email with custom headers sent! Message ID: %s\n", response.ID)
}

func performOAuthFlow(ctx context.Context, client *gmail.Client) (*oauth2.Token, error) {
	authURL := client.GetAuthURL("state")
	fmt.Printf("\nVisit this URL to authorize the application:\n%s\n\n", authURL)
	fmt.Print("Enter the authorization code: ")

	var code string
	if _, err := fmt.Scan(&code); err != nil {
		return nil, fmt.Errorf("failed to read code: %w", err)
	}

	token, err := client.ExchangeCode(ctx, code)
	if err != nil {
		return nil, fmt.Errorf("failed to exchange code: %w", err)
	}

	return token, nil
}

func loadToken() (*oauth2.Token, error) {
	data, err := os.ReadFile("../token.json")
	if err != nil {
		return nil, err
	}

	var token oauth2.Token
	if err := json.Unmarshal(data, &token); err != nil {
		return nil, err
	}

	return &token, nil
}

func saveToken(token *oauth2.Token) error {
	data, err := json.Marshal(token)
	if err != nil {
		return err
	}

	return os.WriteFile("../token.json", data, 0600)
}
